version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2

_snyk_options: &snyk_options
  project: "${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}"
  organization: "legal-aid-agency"
  severity-threshold: "high"
  fail-on-issues: false
  monitor-on-build: false
  token-variable: SNYK_TOKEN
  additional-arguments: --policy-path=.snyk

# ------------------
# EXECUTORS
# ------------------
executors:
  openjdk-executor:
    resource_class: medium
    docker:
      - image: cimg/openjdk:17.0.6

# ------------------
# COMMANDS
# ------------------
commands:
  publish_artefact_rest_client:
    description: >
      Publish artefact to Maven Central
    parameters:
      type:
        type: enum
        default: "minor"
        enum: ["minor", "major", "patch", "snapshot"]
        description: Specifies the type of release (major, minor, patch, snapshot)
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-cache-{{ checksum "crime-commons-spring-boot-starter-rest-client/build.gradle" }}
      - when:
          condition:
            equal: ["major", << parameters.type >>]
          steps:
            - run:
                name: Publish major release to Maven Central
                command: ./gradlew final -Prelease.scope=major publish publishToSonatype closeAndReleaseSonatypeStagingRepository
      - when:
          condition:
            equal: ["minor", << parameters.type >>]
          steps:
            - run:
                name: Publish minor release to Maven Central
                command: ./gradlew final publishToSonatype closeAndReleaseSonatypeStagingRepository

      - when:
          condition:
            equal: ["patch", << parameters.type >>]
          steps:
            - run:
                name: Publish patch release to Maven Central
                command: ./gradlew final -Prelease.scope=patch publishToSonatype closeAndReleaseSonatypeStagingRepository

      - when:
          condition:
            equal: ["snapshot", << parameters.type >>]
          steps:
            - run:
                name: Publish snapshot release to Maven Central
                command: ./gradlew snapshot publishToSonatype closeAndReleaseSonatypeStagingRepository

  publish_artefact_crime_commons_classes:
    description: >
      Publish artefact to Maven Central
    parameters:
      type:
        type: enum
        default: "minor"
        enum: ["minor", "major", "patch", "snapshot"]
        description: Specifies the type of release (major, minor, patch, snapshot)
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-cache-{{ checksum "crime-commons-classes/build.gradle" }}
      - when:
          condition:
            equal: ["major", << parameters.type >>]
          steps:
            - run:
                name: Publish major release to Maven Central
                command: ./gradlew final -Prelease.scope=major publish publishToSonatype closeAndReleaseSonatypeStagingRepository
      - when:
          condition:
            equal: ["minor", << parameters.type >>]
          steps:
            - run:
                name: Publish minor release to Maven Central
                command: ./gradlew final publishToSonatype closeAndReleaseSonatypeStagingRepository

      - when:
          condition:
            equal: ["patch", << parameters.type >>]
          steps:
            - run:
                name: Publish patch release to Maven Central
                command: ./gradlew final -Prelease.scope=patch publishToSonatype closeAndReleaseSonatypeStagingRepository

      - when:
          condition:
            equal: ["snapshot", << parameters.type >>]
          steps:
            - run:
                name: Publish snapshot release to Maven Central
                command: ./gradlew snapshot publishToSonatype closeAndReleaseSonatypeStagingRepository

  authenticate_host:
    description: >
      Add github.com to known hosts
    steps:
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts

# ------------------
# JOB 1: For crime-commons-spring-boot-starter-rest-client
# ------------------
jobs:
  build_and_test_rest_client:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=t --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED"
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-spring-boot-starter-rest-client
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-cache-{{ checksum "crime-commons-spring-boot-starter-rest-client/build.gradle" }}
      - run:
          name: Build library and run tests
          command: ./gradlew shadowJar crime-commons-spring-boot-starter-rest-client:build
      - run:
          name: Run SonarQube
          command: ./gradlew sonar
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "crime-commons-spring-boot-starter-rest-client/build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  snyk_scan_rest_client:
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-spring-boot-starter-rest-client
    steps:
      - checkout:
          path: ~/laa-crime-commons/crime-commons-spring-boot-starter-rest-client
      - snyk/scan:
          <<: *snyk_options

  publish_major_release_rest_client:
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-spring-boot-starter-rest-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:a8:8f:5d:a4:fc:7e:03:b2:0f:e2:a5:0a:ae:8f:8b"
      - authenticate_host
      - publish_artefact_rest_client:
          type: major

  publish_minor_release_rest_client:
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-spring-boot-starter-rest-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:a8:8f:5d:a4:fc:7e:03:b2:0f:e2:a5:0a:ae:8f:8b"
      - authenticate_host
      - publish_artefact_rest_client:
          type: minor

  publish_patch_release_rest_client:
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-spring-boot-starter-rest-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:a8:8f:5d:a4:fc:7e:03:b2:0f:e2:a5:0a:ae:8f:8b"
      - authenticate_host
      - publish_artefact_rest_client:
          type: patch

  publish_snapshot_release_rest_client:
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-spring-boot-starter-rest-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:a8:8f:5d:a4:fc:7e:03:b2:0f:e2:a5:0a:ae:8f:8b"
      - authenticate_host
      - publish_artefact_rest_client:
          type: snapshot

# ------------------------------------
# For crime-commons-classes
# -----------------------------------

  build_and_test_crime_commons_classes:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=t --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED"
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-classes
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-cache-{{ checksum "crime-commons-classes/build.gradle" }}
      - run:
          name: Build library and run tests
          command: ./gradlew crime-commons-classes:build
      - run:
          name: Run SonarQube
          command: ./gradlew sonar
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "crime-commons-classes/build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  snyk_scan_crime_commons_classes:
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-classes
    steps:
      - checkout:
          path: ~/laa-crime-commons/crime-commons-classes
      - snyk/scan:
          <<: *snyk_options

  publish_major_release_crime_commons_classes:
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-classes
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:a8:8f:5d:a4:fc:7e:03:b2:0f:e2:a5:0a:ae:8f:8b"
      - authenticate_host
      - publish_artefact_crime_commons_classes:
          type: major

  publish_minor_release_crime_commons_classes:
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-classes
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:a8:8f:5d:a4:fc:7e:03:b2:0f:e2:a5:0a:ae:8f:8b"
      - authenticate_host
      - publish_artefact_crime_commons_classes:
          type: minor

  publish_patch_release_crime_commons_classes:
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-classes
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:a8:8f:5d:a4:fc:7e:03:b2:0f:e2:a5:0a:ae:8f:8b"
      - authenticate_host
      - publish_artefact_crime_commons_classes:
          type: patch

  publish_snapshot_release_crime_commons_classes:
    executor: openjdk-executor
    working_directory: ~/laa-crime-commons/crime-commons-classes
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:a8:8f:5d:a4:fc:7e:03:b2:0f:e2:a5:0a:ae:8f:8b"
      - authenticate_host
      - publish_artefact_crime_commons_classes:
          type: snapshot

# ------------------
# WORKFLOWS
# ------------------
workflows:
  version: 2

  build_publish_rest_client_main:
    jobs:
      - build_and_test_rest_client:
          filters:
            branches:
              only:
                - main
          context: SonarCloud

      - snyk_scan_rest_client:
          requires:
            - build_and_test_rest_client

      - major_release_approval:
          type: approval
          requires:
            - snyk_scan_rest_client

      - publish_major_release_rest_client:
          requires:
            - major_release_approval

      - minor_release_approval:
          type: approval
          requires:
            - snyk_scan_rest_client

      - publish_minor_release_rest_client:
          requires:
            - minor_release_approval

      - patch_release_approval:
          type: approval
          requires:
            - snyk_scan_rest_client

      - publish_patch_release_rest_client:
          requires:
            - patch_release_approval

  build_publish_rest_client_branch:
    jobs:
      - branch_build_approval:
          type: approval
          filters:
            branches:
              ignore:
                - main

      - build_and_test_rest_client:
          requires:
            - branch_build_approval
          context: SonarCloud

      - snyk_scan_rest_client:
          requires:
            - build_and_test_rest_client

      - snapshot_release_approval:
          type: approval
          requires:
            - snyk_scan_rest_client

      - publish_snapshot_release_rest_client:
          requires:
            - snapshot_release_approval

  build_publish_crime_commons_classes_main:
    jobs:
      - build_and_test_crime_commons_classes:
          filters:
            branches:
              only:
                - main
          context: SonarCloud

      - snyk_scan_crime_commons_classes:
          requires:
            - build_and_test_crime_commons_classes

      - major_release_approval:
          type: approval
          requires:
            - snyk_scan_crime_commons_classes

      - publish_major_release_crime_commons_classes:
          requires:
            - major_release_approval

      - minor_release_approval:
          type: approval
          requires:
            - snyk_scan_crime_commons_classes

      - publish_minor_release_crime_commons_classes:
          requires:
            - minor_release_approval

      - patch_release_approval:
          type: approval
          requires:
            - snyk_scan_crime_commons_classes

      - publish_patch_release_crime_commons_classes:
          requires:
            - patch_release_approval

  build_publish_crime_commons_classes_branch:
    jobs:
      - branch_build_approval:
          type: approval
          filters:
            branches:
              ignore:
                - main

      - build_and_test_crime_commons_classes:
          requires:
            - branch_build_approval
          context: SonarCloud

      - snyk_scan_crime_commons_classes:
          requires:
            - build_and_test_crime_commons_classes

      - snapshot_release_approval:
          type: approval
          requires:
            - snyk_scan_crime_commons_classes

      - publish_snapshot_release_crime_commons_classes:
          requires:
            - snapshot_release_approval